#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

i=0
j=1
var="Hours:"

while [ $i -le 12 ]
do
	echo $var $i
	while [ $j -le 59 ]
	do
		echo $j
		((j++))
	done
	j=1
	((i++))
done
